config/routes.rb
Rails.application.routes.draw do

  get 'landings/index'

  root 'landings#index'

  resources :pokemons do
    resources :sightings, except: [:index, :show]
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  resources :users, only: [:index] do
    resources :poke_desks, only: [:index, :create] do
      member do
        get 'levelup'
        get 'change'
      end
    end
  end

    namespace :admin do
      resources :users
    end

end

app/models/poke_desk.rb
class PokeDesk < ActiveRecord::Base
  belongs_to :user
  belongs_to :pokemon

  before_save :set_default_level

  def set_default_level
    self.level = level || 5
  end
end

app/controllers/poke_desks_controller.rb
class PokeDesksController < ApplicationController
  before_action :set_poke_desk, only: [:levelup, :change]

  def index
    @user = User.find(params[:user_id])
    @poke_desks = PokeDesk.where(user: @user).order(:id)

    @pokemons = Pokemon.all
    @pokemons = Pokemon.filter_by_name(params[:search]) if params[:search].present?
  end

  def create
    @poke_desk = PokeDesk.new(poke_desk_params)
    @poke_desk.user_id = params[:user_id]

    respond_to do |format|
      if @poke_desk.save
        format.html { redirect_to user_poke_desks_path(params[:user_id]), notice: 'Poke desk was successfully created.' }
        format.json { render :show, status: :created, location: @poke_desk }
      else
        format.html { render :new }
        format.json { render json: @poke_desk.errors, status: :unprocessable_entity }
      end
    end
  end

  def levelup
    @poke_desk.level += 1
    @poke_desk.save
    redirect_to user_poke_desks_path(@poke_desk.user)
  end

  def change

    # sobre escribo el user del poke_desk actual, con el current_user
    @poke_desk.user = current_user

    # obtego un poke_desk del current_user User.order("RANDOM()").first
    poke_desk = PokeDesk.where(user: current_user).order("RANDOM()").first
    # le cambio user del poke_desk del current_user, por el del user del poke_desk actual
    poke_desk.user_id = params[:user_id]

    if @poke_desk.save && poke_desk.save
      redirect_to user_poke_desks_path(params[:user_id]), notice: 'Poke desk was successfully changed.'
    else
      redirect_to user_poke_desks_path(params[:user_id]), alert: 'Poke desk wasnt successfully changed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poke_desk
      @poke_desk = PokeDesk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poke_desk_params
      params.require(:poke_desk).permit(:level, :pokemon_id)
    end
end

app/helpers/poke_desks_helper.rb
module PokeDesksHelper
end

app/views/poke_desks/index.html.erb
<div class="col-md-8">
  <h1>PokeDesks of <%= @user.name %> </h1>
  <% @poke_desks.each do |poke_desk| %>
    <div class=" col-md-3 panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><%= poke_desk.pokemon.name %></h3>
      </div>
      <div class="panel-body">
        <p>
          Level: <%= poke_desk.level %>
          <% if !current_user.nil? && current_user.id == @user.id %>
            <a href=<%= levelup_user_poke_desk_path(@user, poke_desk.id) %>>
              <span class="glyphicon glyphicon-menu-up" aria-hidden="true"></span>
            </a>
          <% end %>
        </p>
        <p><%= poke_desk.pokemon.description %></p>
        <p>
          <% if !current_user.nil? && current_user.id != @user.id %>
            <a href=<%= change_user_poke_desk_path(@user, poke_desk.id) %>>
              Change <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span>
            </a>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
</div>
<% if !current_user.nil? && current_user.id == @user.id %>
  <div class="col-md-4">
    <h1>List of Pokemons </h1>
    <div class="well">
      <div class="row">
        <%= form_tag user_poke_desks_path, method: :get, class: "navbar-form navbar-left search-form" do %>
          <%= text_field_tag(
              :search,
              params[:search],
              placeholder: "Search",
              class: "form-control"
          ) %>
          <%= submit_tag("Search", class: "form-control") %>
        <% end %>
      </div>
      <div class="row">
        <% @pokemons.each do |pokemon| %>
          <%= form_for [@user, PokeDesk.new] do |f| %>
            <div class="input-group">
              <span class="input-group-btn">
                <%= f.submit("<<", class: "btn btn-default") %>
              </span>
              <%= f.text_field(
                  :pokemon_id,
                  value: pokemon.name,
                  class: "form-control",
                  readonly: true
              ) %>
              <%= f.hidden_field(:pokemon_id, value: pokemon.id) %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>