config/routes.rb
Rails.application.routes.draw do

  get 'landings/index'

  root 'landings#index'

  resources :pokemons do
    resources :sightings, except: [:index, :show]
  end

  devise_for :users, controllers: {
        registrations: 'users/registrations',
        sessions: 'users/sessions'
      }

  resources :users, only: [:index] do
    resources :poke_desks, only: [:index, :create] do
      member do
        get 'levelup'
        get 'change'
      end
    end
  end

    namespace :admin do
      resources :users
    end

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
  has_many :poke_desks, dependent: :destroy
  has_many :users, through: :poke_desks
  has_many :sightings, dependent: :destroy

  scope :filter_by_name, ->(query) { where("name like ?", "%#{query}%")  }
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :description)
    end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
  <h1>Listing Pokemons</h1>
<div class="row">
  <%= link_to 'New Pokemon', new_pokemon_path %>
</div>

<% @pokemons.each do |pokemon| %>
  <div class=" col-md-3 panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title"><%= pokemon.name %></h3>
    </div>
    <div class="panel-body">
      <p><%= pokemon.description %></p>
      <p>
        <%= link_to 'Sighting Report', new_pokemon_sighting_path(pokemon.id) %>
      </p>
      <p>
        <%= link_to 'Show', pokemon %> |
        <!-- <%= link_to 'Edit', edit_pokemon_path(pokemon) %> |
        <%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %> -->
      </p>
    </div>
  </div>
<% end %>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.name %></h1>


<p>
  <strong>Description:</strong>
  <%= @pokemon.description %>
</p>
<br>
<%= link_to 'Edit Pokemon', edit_pokemon_path(@pokemon) %> |

<h3>Listing Sightings</h3>
<%= link_to 'New Sighting', new_pokemon_sighting_path(@pokemon) %>
<div class="row">
  <% @pokemon.sightings.each do |sighting| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag sighting.picture.thumb %>
        <div class="caption">
          <h3>Information</h3>
          <p><%= sighting.information %></p>
          <p>
            <%= link_to(
              'Edit',
              edit_pokemon_sighting_path(@pokemon, sighting),
              class: "btn btn-primary",
              role: "button"
            ) %>
            <%= link_to(
              'Destroy',
              [@pokemon, sighting],
              class: "btn btn-default",
              method: :delete,
              data: { confirm: 'Are you sure?' },
              role: "button"
            ) %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>


<!-- <table class="table">
  <thead>
    <tr>
      <th>Information</th>
      <th>Picture</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemon.sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.information %></td>
        <td><%= image_tag sighting.picture %></td>
        <td><%= link_to 'Edit', edit_pokemon_sighting_path(@pokemon, sighting), class: "btn btn-primary" %></td>
        <td><%= link_to 'Destroy', [@pokemon, sighting], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 -->
<br>
<%= link_to 'Back', pokemons_path %>